# Define target output
target: bit

# Define target part
export PRJ_PART = XCZU67DR-FSVE1156-2-I

# Define TOP directory
export TOP_DIR = $(abspath $(PWD)/../..)

# Use top level makefile
include ../shared_version.mk
include $(TOP_DIR)/submodules/ruckus/system_vivado.mk
